version: "3.7"
services:
  jupyter-lab:
    build: 
      context: .
      dockerfile: Dockerfile.jupyter
    environment:
      - JUPYTER_TOKEN=codeop
    volumes:
      - ./nbs/:/home/jovyan/work
    ports:
      - 8888:8888

  mongo:
    container_name: mongodb
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
  
  mongo-seed:
    env_file:
      - .env
    build:
      context: ./mongo_seed
      dockerfile: Dockerfile
      args:
          - DATABASE_URI=$DATABASE_URI
          - USERNAME=$MONGO_INITDB_ROOT_USERNAME
          - PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    depends_on:
      - mongo

